# Generated by Django 6.0.5 on 2026-06-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='direccion_fiscal',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='movimiento',
            old_name='fecha_creacion',
            new_name='creado',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='condicion_fiscal',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='direccion_real',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='inicio_actividades',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='inicio_contable',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='presidente',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='telefono1',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='telefono2',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='vicepresidente',
        ),
        migrations.RemoveField(
            model_name='rubro',
            name='empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
