# Generated by Django 6.0.5 on 2026-06-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_direccion_fiscal_empresa_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='direccion',
            new_name='direccion_fiscal',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='telefono',
        ),
        migrations.AddField(
            model_name='empresa',
            name='acta',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='condicion_fiscal',
            field=models.CharField(blank=True, choices=[('Responsable inscripto', 'Responsable inscripto'), ('Monotributo', 'Monotributo'), ('Exento', 'Exento'), ('Consumidor final', 'Consumidor final')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='designacion',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_real',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estatuto',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inicio_actividades',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inicio_contable',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='presidente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='vicepresidente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='movimientos/'),
        ),
    ]
