# Generated by Django 6.0.5 on 2026-06-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_direccion_empresa_direccion_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Vencido', 'Vencido')], default='Pendiente', max_length=20),
        ),
    ]
