# Generated by Django 6.0.5 on 2026-06-07 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_movimiento_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='empresa',
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('presidente', models.CharField(blank=True, max_length=150, null=True)),
                ('vicepresidente', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='usuarios.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ejercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='usuarios.ejercicio'),
        ),
    ]
