# Generated by Django 6.0.5 on 2026-06-15 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_movimiento_empresa_ejercicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Casa Central', 'Casa Central'), ('Sucursal', 'Sucursal'), ('Deposito', 'Deposito'), ('Mostrador', 'Mostrador')], max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros', to='usuarios.empresa')),
            ],
        ),
    ]
