# Generated by Django 6.0.5 on 2026-06-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fecha_acta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_designacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_estatuto',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
