# Generated by Django 6.0.5 on 2026-07-11 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_empresa_fecha_acta_empresa_fecha_designacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos', to='usuarios.empresa')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
    ]
