# Generated by Django 6.0.5 on 2026-07-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_banco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['razon_social']},
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='telefono',
            new_name='contacto1_telefono',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto1_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto1_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto2_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto2_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto2_telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='localidad',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(max_length=13),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'cuit'), name='proveedor_cuit_unico_por_empresa'),
        ),
    ]
