# Generated by Django 6.0.5 on 2026-07-29 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_proveedor_razon_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='rubro',
        ),
        migrations.RemoveField(
            model_name='subrubro',
            name='rubro',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='subrubro',
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_gasto', to='usuarios.empresa')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='usuarios.tipogasto'),
        ),
        migrations.CreateModel(
            name='TipoGastoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_tipos_gasto', to='usuarios.proveedor')),
                ('tipo_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_proveedores', to='usuarios.tipogasto')),
            ],
            options={
                'ordering': ['proveedor__razon_social'],
            },
        ),
        migrations.DeleteModel(
            name='Rubro',
        ),
        migrations.DeleteModel(
            name='Subrubro',
        ),
        migrations.AddConstraint(
            model_name='tipogasto',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='tipo_gasto_nombre_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tipogastoproveedor',
            constraint=models.UniqueConstraint(fields=('tipo_gasto', 'proveedor'), name='tipo_gasto_proveedor_unico'),
        ),
    ]
