# Generated by Django 6.0.5 on 2026-08-02 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_remove_movimiento_rubro_remove_subrubro_rubro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('sitio', models.CharField(blank=True, max_length=255)),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('contrasena_cifrada', models.TextField(blank=True)),
                ('referencia_recuperacion_1', models.CharField(blank=True, max_length=255)),
                ('referencia_recuperacion_2', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claves', to='usuarios.empresa')),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('empresa', 'nombre'), name='unique_gestion_clave_activa_empresa_nombre')],
            },
        ),
    ]
