# Generated by Django 6.0.5 on 2026-08-02 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_gestionclave'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_recurso', models.CharField(choices=[('Persona', 'Persona'), ('Vehiculo', 'Vehículo'), ('Inmueble', 'Inmueble'), ('Equipo', 'Equipo'), ('Otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('centro_operativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos_operativos', to='usuarios.centrooperativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_operativos', to='usuarios.empresa')),
            ],
            options={
                'ordering': ['tipo_recurso', 'nombre'],
            },
        ),
    ]
