# Generated by Django 6.0.5 on 2026-08-03 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_crear_recurso_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='centro_operativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='usuarios.centrooperativo'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='recurso_operativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='usuarios.recursooperativo'),
        ),
    ]
