# Generated by Django 6.0.5 on 2026-08-04 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_movimiento_centro_operativo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimiento',
            old_name='fecha_pago',
            new_name='fecha_registro',
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_cuenta', models.CharField(choices=[('CuentaCorriente', 'Cuenta corriente'), ('CajaAhorro', 'Caja de ahorro'), ('Otra', 'Otra')], max_length=30)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='ARS', max_length=10)),
                ('numero_cuenta', models.CharField(blank=True, max_length=80)),
                ('cbu', models.CharField(blank=True, max_length=22)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='usuarios.banco')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='usuarios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('importe_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='usuarios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DebitoAutomaticoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_debito', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/debitos_automaticos/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debitos_automaticos_pago', to='usuarios.cuentabancaria')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debitos_automaticos', to='usuarios.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_instrumento', models.CharField(choices=[('Cheque', 'Cheque físico'), ('ECheq', 'e-Cheq')], max_length=20)),
                ('origen', models.CharField(choices=[('Propio', 'Propio'), ('Tercero', 'Tercero')], max_length=20)),
                ('tipo_cheque', models.CharField(choices=[('Comun', 'Cheque Común'), ('Diferido', 'Cheque Diferido')], max_length=20)),
                ('numero', models.CharField(max_length=30)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_emision', models.DateField()),
                ('fecha_acreditacion', models.DateField(blank=True, null=True)),
                ('quien_entrega', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('EnCartera', 'En cartera'), ('Entregado', 'Entregado'), ('Depositado', 'Depositado'), ('Cobrado', 'Cobrado'), ('Debitado', 'Debitado'), ('Vencido', 'Vencido'), ('Rechazado', 'Rechazado'), ('Devuelto', 'Devuelto'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/cheques/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='usuarios.banco')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='usuarios.empresa')),
                ('cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='usuarios.cuentabancaria')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='usuarios.pago')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cantidad_cuotas', models.PositiveIntegerField()),
                ('fecha_primer_vencimiento', models.DateField()),
                ('periodicidad', models.CharField(choices=[('Mensual', 'Mensual'), ('Quincenal', 'Quincenal'), ('Semanal', 'Semanal'), ('Otra', 'Otra')], default='Mensual', max_length=20)),
                ('modalidad_pago', models.CharField(choices=[('Manual', 'Pago manual'), ('DebitoAutomatico', 'Débito automático')], default='Manual', max_length=30)),
                ('referencia_debito', models.CharField(blank=True, max_length=150)),
                ('tasa_interes', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Activo', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('cuenta_debito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_debito_automatico', to='usuarios.cuentabancaria')),
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='plan_pago', to='usuarios.movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('punitorios', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Pagada', 'Pagada'), ('Vencida', 'Vencida'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='usuarios.planpago')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='RetencionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/retenciones/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones', to='usuarios.pago')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/tarjetas/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tarjeta', to='usuarios.pago')),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/transferencias/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_pago', to='usuarios.cuentabancaria')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='usuarios.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_origen', models.CharField(choices=[('Movimiento', 'Movimiento'), ('CuotaPlan', 'Cuota de plan'), ('Cheque', 'Cheque / e-Cheq')], max_length=30)),
                ('fecha_vencimiento', models.DateField()),
                ('importe_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('importe_pendiente', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Pagado', 'Pagado'), ('Vencido', 'Vencido'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vencimientos', to='usuarios.banco')),
                ('cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vencimientos', to='usuarios.cheque')),
                ('cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vencimientos', to='usuarios.cuentabancaria')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vencimientos', to='usuarios.cuotaplan')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vencimientos', to='usuarios.empresa')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vencimientos', to='usuarios.movimiento')),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alerta', models.DateField()),
                ('dias_anticipacion', models.PositiveIntegerField(default=3)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Atendida', 'Atendida'), ('Reprogramada', 'Reprogramada'), ('Cancelada', 'Cancelada')], default='Activa', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('atendida_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('vencimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='usuarios.vencimiento')),
            ],
            options={
                'ordering': ['fecha_alerta', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_pago', to='usuarios.movimiento')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_pago', to='usuarios.cuotaplan')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='usuarios.pago')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cuota__isnull', True), ('movimiento__isnull', False)), models.Q(('cuota__isnull', False), ('movimiento__isnull', True)), _connector='OR'), name='aplicacion_pago_un_solo_destino'), models.CheckConstraint(condition=models.Q(('importe__gt', 0)), name='aplicacion_pago_importe_positivo')],
            },
        ),
        migrations.AddConstraint(
            model_name='cuotaplan',
            constraint=models.UniqueConstraint(fields=('plan', 'numero'), name='cuota_numero_unico_por_plan'),
        ),
        migrations.AddConstraint(
            model_name='vencimiento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cheque__isnull', True), ('cuota__isnull', True), ('movimiento__isnull', False)), models.Q(('cheque__isnull', True), ('cuota__isnull', False), ('movimiento__isnull', True)), models.Q(('cheque__isnull', False), ('cuota__isnull', True), ('movimiento__isnull', True)), _connector='OR'), name='vencimiento_un_solo_origen'),
        ),
    ]
