# Generated by Django 6.0.5 on 2026-08-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_rename_fecha_pago_movimiento_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='dias_aviso_cheques_propios',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
