# Generated by Django 6.0.5 on 2026-08-08 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'usuarios',
            '0018_cuentabancaria_dias_aviso_cheques_propios'
        ),
    ]

    operations = [

        migrations.RenameModel(
            old_name='TransferenciaPago',
            new_name='OperacionBancariaPago',
        ),


        migrations.RenameField(
            model_name='operacionbancariapago',
            old_name='cuenta_bancaria',
            new_name='cuenta_origen',
        ),


        migrations.AlterField(
            model_name='operacionbancariapago',
            name='cuenta_origen',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='operaciones_pago_origen',
                to='usuarios.cuentabancaria',
            ),
        ),


        migrations.AddField(
            model_name='operacionbancariapago',
            name='tipo_operacion',
            field=models.CharField(
                choices=[
                    (
                        'Transferencia',
                        'Transferencia'
                    ),
                    (
                        'Deposito',
                        'Depósito'
                    ),
                ],
                default='Transferencia',
                max_length=20,
            ),
        ),


        migrations.AddField(
            model_name='operacionbancariapago',
            name='banco_destino',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='operaciones_pago_destino',
                to='usuarios.banco',
            ),
        ),


        migrations.AddField(
            model_name='operacionbancariapago',
            name='referencia_destino',
            field=models.CharField(
                blank=True,
                max_length=150,
            ),
        ),


        migrations.AddField(
            model_name='operacionbancariapago',
            name='moneda',
            field=models.CharField(
                choices=[
                    (
                        'ARS',
                        'Pesos'
                    ),
                    (
                        'USD',
                        'Dólares'
                    ),
                ],
                default='ARS',
                max_length=10,
            ),
        ),


        migrations.AlterField(
            model_name='operacionbancariapago',
            name='importe',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
            ),
        ),


        migrations.AlterField(
            model_name='operacionbancariapago',
            name='comprobante',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='pagos/operaciones_bancarias/',
            ),
        ),


        migrations.AlterField(
            model_name='operacionbancariapago',
            name='pago',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='operaciones_bancarias',
                to='usuarios.pago',
            ),
        ),

    ]