# Generated by Django 6.0.5 on 2026-08-08 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_operacionbancariapago_delete_transferenciapago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacionbancariapago',
            name='referencia',
        ),
        migrations.AlterField(
            model_name='operacionbancariapago',
            name='banco_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_pago_destino', to='usuarios.banco'),
        ),
    ]
