# Generated by Django 6.0.5 on 2026-08-13 17:24

import django.db.models.deletion
from django.db import migrations, models


def migrar_centros_actuales(
    apps,
    schema_editor
):

    RecursoOperativo = apps.get_model(
        'usuarios',
        'RecursoOperativo'
    )

    RecursoOperativoCentro = apps.get_model(
        'usuarios',
        'RecursoOperativoCentro'
    )


    for recurso in RecursoOperativo.objects.all():

        if not recurso.centro_operativo_id:

            continue


        RecursoOperativoCentro.objects.get_or_create(

            recurso_operativo_id=recurso.id,

            centro_operativo_id=recurso.centro_operativo_id

        )


class Migration(migrations.Migration):

    dependencies = [
        (
            'usuarios',
            '0020_remove_operacionbancariapago_referencia_and_more'
        ),
    ]

    operations = [

        migrations.CreateModel(
            name='RecursoOperativoCentro',

            fields=[

                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),

                (
                    'creado',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),

                (
                    'centro_operativo',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='relaciones_recursos',
                        to='usuarios.centrooperativo'
                    )
                ),

                (
                    'recurso_operativo',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='relaciones_centros',
                        to='usuarios.recursooperativo'
                    )
                ),

            ],

            options={

                'constraints': [

                    models.UniqueConstraint(
                        fields=(
                            'recurso_operativo',
                            'centro_operativo'
                        ),
                        name='recurso_operativo_centro_unico'
                    )

                ],

            },
        ),


        migrations.RunPython(
            migrar_centros_actuales,
            migrations.RunPython.noop
        ),

    ]