# Generated by Django 6.0.5 on 2026-08-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_recursooperativocentro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recursooperativo',
            name='centro_operativo',
        ),
    ]
