# Generated by Django 6.0.5 on 2026-08-17 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_remove_recursooperativo_centro_operativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetapago',
            name='cuotas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tarjetapago',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarjetapago',
            name='intereses_financiacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='tarjetapago',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='tarjetapago',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas', to='usuarios.pago'),
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_tarjeta', models.CharField(choices=[('Credito', 'Crédito'), ('Debito', 'Débito')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas', to='usuarios.cuentabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='usuarios.empresa')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='tarjetapago',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_pago', to='usuarios.tarjeta'),
        ),
        migrations.AddConstraint(
            model_name='tarjeta',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='tarjeta_empresa_nombre_unico'),
        ),
    ]
