# Generated by Django 6.0.5 on 2026-08-17 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_tarjetapago_cuotas_tarjetapago_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetapago',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarjetapago',
            name='tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_pago', to='usuarios.tarjeta'),
        ),
    ]
