# Generated by Django 6.0.5 on 2026-08-18 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_alter_tarjetapago_fecha_alter_tarjetapago_tarjeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono_personal', models.CharField(blank=True, max_length=30)),
                ('telefono_laboral', models.CharField(blank=True, max_length=30)),
                ('direccion_laboral', models.CharField(blank=True, max_length=255)),
                ('estado_acceso', models.CharField(choices=[('pendiente', 'Pendiente'), ('demo', 'Demo'), ('activo', 'Activo'), ('bloqueado', 'Bloqueado')], default='demo', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_ordenaclick', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
