# Generated by Django 6.0.5 on 2026-08-19 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones', to='usuarios.empresa')),
            ],
            options={
                'ordering': ['tipo'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'tipo'), name='retencion_empresa_tipo_unico')],
            },
        ),
    ]
