# Generated by Django 6.0.5 on 2026-08-22 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_retencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='ajuste_redondeo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='usuarios.empresa'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='iva_105',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='iva_21',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='iva_27',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='ARS', max_length=10),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='neto_gravado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='no_gravado_exento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='percepcion_ganancias',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='percepcion_iibb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='percepcion_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='percepcion_tasas_municipales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='usuarios.proveedor'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='recargos_intereses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_comprobante',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='ejercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='usuarios.ejercicio'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Pagado', 'Pagado'), ('Vencido', 'Vencido'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
    ]
