# Generated by Django 6.0.5 on 2026-08-30 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_movimiento_ajuste_redondeo_movimiento_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='cuenta_debito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_debito_automatico', to='usuarios.cuentabancaria'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='modalidad_pago',
            field=models.CharField(choices=[('Manual', 'Pago manual'), ('DebitoAutomatico', 'Débito automático')], default='Manual', max_length=30),
        ),
    ]
