# Generated by Django 6.0.5 on 2026-08-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_movimiento_cuenta_debito_movimiento_modalidad_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitoautomaticopago',
            name='intereses_mora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
