# Generated by Django 6.0.5 on 2026-09-18 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_empresa_propietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cliente', models.CharField(max_length=50)),
                ('cuit', models.CharField(blank=True, max_length=11)),
                ('razon_social', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('celular', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('centro_operativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='usuarios.centrooperativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='usuarios.empresa')),
            ],
            options={
                'ordering': ['centro_operativo__nombre', 'numero_cliente'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'centro_operativo', 'numero_cliente'), name='cliente_numero_unico_por_centro'), models.UniqueConstraint(condition=models.Q(('cuit', ''), _negated=True), fields=('empresa', 'centro_operativo', 'cuit'), name='cliente_cuit_unico_por_centro')],
            },
        ),
    ]
