# Generated by Django 6.0.5 on 2026-09-23 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('centro_operativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='usuarios.centrooperativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='usuarios.empresa')),
            ],
            options={
                'ordering': ['centro_operativo__nombre', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'centro_operativo', 'nombre'), name='caja_nombre_unico_por_centro')],
            },
        ),
    ]
