# Generated by Django 6.0.5 on 2026-09-23 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_caja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(max_length=200)),
                ('vendedor_referencia', models.CharField(blank=True, max_length=150)),
                ('total_declarado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobranzas', to='usuarios.caja')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobranzas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobranzas', to='usuarios.empresa')),
            ],
            options={
                'ordering': ['-fecha', '-creado'],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_declarado__gt', 0)), name='cobranza_total_declarado_positivo')],
            },
        ),
    ]
