# Generated by Django 6.0.5 on 2026-09-23 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0034_movimientocaja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheque',
            options={'ordering': ['fecha_acreditacion', 'fecha_vencimiento', 'numero']},
        ),
        migrations.AddField(
            model_name='cheque',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='usuarios.caja'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='usuarios.cliente'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='cobranza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='usuarios.cobranza'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('Entregado', 'Entregado'), ('Depositado', 'Depositado'), ('Cobrado', 'Cobrado'), ('Debitado', 'Debitado'), ('Vencido', 'Vencido'), ('Rechazado', 'Rechazado'), ('Devuelto', 'Devuelto'), ('Anulado', 'Anulado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='tipo_cheque',
            field=models.CharField(choices=[('Comun', 'Cheque común'), ('Diferido', 'Cheque diferido')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='cheque',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gt', 0)), name='cheque_importe_positivo'),
        ),
    ]
