# Generated by Django 6.0.5 on 2026-09-27 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_alter_cheque_options_cheque_caja_cheque_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cobranza',
            name='cobranza_total_declarado_positivo',
        ),
        migrations.AlterField(
            model_name='cobranza',
            name='total_declarado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddConstraint(
            model_name='cobranza',
            constraint=models.CheckConstraint(condition=models.Q(('total_declarado__isnull', True), ('total_declarado__gt', 0), _connector='OR'), name='cobranza_total_declarado_positivo'),
        ),
    ]
