# Generated by Django 6.0.5 on 2026-09-27 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0036_remove_cobranza_cobranza_total_declarado_positivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionUsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jerarquia', models.CharField(choices=[('admin_general', 'Administrador general'), ('admin_centro', 'Administrador de sucursal'), ('colaborador', 'Colaborador')], default='colaborador', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_usuarios', to='usuarios.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario__username'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'usuario'), name='uniq_asignacion_usuario_empresa')],
            },
        ),
    ]
