# Generated by Django 6.0.5 on 2026-09-27 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_asignacionusuarioempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionusuarioempresa',
            name='centro_operativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_usuarios', to='usuarios.centrooperativo'),
        ),
        migrations.AlterField(
            model_name='asignacionusuarioempresa',
            name='jerarquia',
            field=models.CharField(choices=[('admin_general', 'Administrador general'), ('admin_centro', 'Administrador'), ('colaborador', 'Colaborador')], default='colaborador', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='asignacionusuarioempresa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('centro_operativo__isnull', False), ('jerarquia', 'admin_centro')), models.Q(('centro_operativo__isnull', True), ('jerarquia__in', ['admin_general', 'colaborador'])), _connector='OR'), name='asignacion_jerarquia_centro_coherente'),
        ),
    ]
